### ISSUE TITLE
I wonder if equation (1) in paper is something wrong.

### ISSUE THREAD

**Issue by sonack** [weijiawu/Unconstrained-Text-Detection-with-Box-Supervisionand-Dynamic-Self-Training#11]
![image](https://user-images.githubusercontent.com/12935189/103198473-5e514700-4923-11eb-92cb-993e497c01c1.png)

I think maybe it should be:

![MommyTalk1609141493388 (2)](https://user-images.githubusercontent.com/12935189/103198845-4e863280-4924-11eb-8290-9ebacf127952.png)

**Comment by sonack** [comment]
@weijiawu 顺便问一下，大概什么时候代码可以ready呀？

**Comment by weijiawu** [comment]
The code will further supplement after the peer review of the paper.

**Comment by sonack** [comment]
> The code will further supplement after the peer review of the paper.

@weijiawu  能回答一下公式1的问题吗？
